from __future__ import annotations

import os
import textwrap
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, Optional

import pandas as pd

from .utils import read_config


@dataclass(frozen=True)
class ConfigSummary:
    analysis_name: str
    total_samples: int
    metadata_columns: list[str]
    recommended_design_columns: list[str]
    lines: list[str]


def _as_str(value) -> str:
    if value is None:
        return ""
    return str(value)


def summarize_config(conf_path: str, *, max_values: int = 12) -> ConfigSummary:
    config = read_config(conf_path)
    conf_df = pd.DataFrame.from_dict(config).T

    total = len(conf_df)
    analysis_name = Path(conf_path).stem

    meta_cols = ("recno", "runno", "searchno", "label")
    metadata_columns = sorted([
        c for c in conf_df.columns if c not in meta_cols and not str(c).startswith("__")
    ])

    value_counts = {col: int(conf_df[col].nunique(dropna=True)) for col in metadata_columns}
    value_count_df = pd.Series(value_counts).to_frame("count")
    value_count_df["ratio"] = value_count_df["count"] / max(total, 1)

    recommended = (
        value_count_df.query("ratio < 1 & ratio > 1/@total")
        .sort_values(by="ratio", ascending=False)
        .index.astype(str)
        .tolist()
    )

    lines: list[str] = []
    lines.append(f"# Config: {conf_path}")
    lines.append(f"# Samples: {total}")
    if not metadata_columns:
        lines.append("# No metadata columns detected beyond recno/runno/searchno/label.")
        return ConfigSummary(
            analysis_name=analysis_name,
            total_samples=total,
            metadata_columns=[],
            recommended_design_columns=[],
            lines=lines,
        )

    lines.append("# Metadata columns (unique values):")
    for col in metadata_columns:
        nunique = int(conf_df[col].nunique(dropna=True))
        if nunique == 0:
            lines.append(f"# - {col}: 0")
            continue
        if nunique > max_values:
            lines.append(f"# - {col}: {nunique}")
            continue
        values = (
            conf_df[col]
            .dropna()
            .astype(str)
            .drop_duplicates()
            .sort_values()
            .tolist()
        )
        preview = ", ".join(values)
        lines.append(f"# - {col}: {nunique} ({preview})")

    if recommended:
        lines.append("# Recommended design columns (good for --formula):")
        for col in recommended:
            lines.append(f"# - {col}")

    return ConfigSummary(
        analysis_name=analysis_name,
        total_samples=total,
        metadata_columns=[str(c) for c in metadata_columns],
        recommended_design_columns=recommended,
        lines=lines,
    )


def render_tacklerun_skeleton(
    *,
    conf_path: str,
    name: Optional[str] = None,
    result_dir: str = "./results",
    data_dir: str = "./data/e2g/",
    file_formats: Iterable[str] = (".png", ".pdf"),
    non_zeros: str = "1",
    normalization_flag: str = "--median",
    only_load_local: bool = False,
) -> str:
    summary = summarize_config(conf_path)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    suggested_design = summary.recommended_design_columns[0] if summary.recommended_design_columns else "group"
    file_format_flags = "\n".join(f"    --file-format {fmt}" for fmt in file_formats)
    only_local_flag = "    --only-load-local" if only_load_local else "    # --only-load-local"

    name_default = name or f'{summary.analysis_name}_$(date +%Y%m%d)'

    script = f"""\
#!/usr/bin/env bash
set -euo pipefail

# Generated by: tackle make-run
# Generated at: {now}
#
# This is a runnable skeleton. Search for "TODO:" to customize.
#
# Tip: Avoid `eval`. Use bash arrays + `\"${{cmd[@]}}\"` to keep quoting safe.

CONF="{conf_path}"   # TODO: set path to your .conf if you move this script

# Results land in: $RESULT_DIR/<config_basename_without_ext>/$NAME/
RESULT_DIR="{result_dir}"   # TODO: base results directory
DATA_DIR="{data_dir}"       # TODO: location of e2g files
NAME="{name_default}"       # TODO: analysis name (subfolder under results)

# Pick a design column for volcano formulas (recommended columns listed below).
DESIGN_COL="{suggested_design}"   # TODO: e.g. group, treat, batch

{os.linesep.join(summary.lines)}

HEADMAIN=(
    --name "$NAME"
    --result-dir "$RESULT_DIR"
    --data-dir "$DATA_DIR"
{file_format_flags}
    {normalization_flag}
    --non-zeros {non_zeros}
    # --nonzero-subgroup "$DESIGN_COL"
{only_local_flag}
    # --group "$DESIGN_COL"   # only for simple 2-group volcano; can block formula-based designs
)

# ---- Volcano settings ----
VOLCANO_FOLDCHANGE=2
VOLCANO_NUMBER_BY="pValue"
VOLCANO_LABEL_SCALE=1.8
VOLCANO_FORMULA="~ 0 + $DESIGN_COL"

# Use a heredoc so you can paste multi-line contrast definitions safely.
# TODO: fill these in. Prefer named contrasts:
#   MyContrast = treatA - treatB,
read -r -d '' VOLCANO_CONTRASTS <<'EOF'
EOF

run_volcano() {{
    tackle "${{HEADMAIN[@]}}" "$CONF" \\
        volcano \\
        --fill-na-zero \\
        --impute-missing-values \\
        --number-by "$VOLCANO_NUMBER_BY" \\
        --foldchange "$VOLCANO_FOLDCHANGE" \\
        --formula "$VOLCANO_FORMULA" \\
        --contrasts "$VOLCANO_CONTRASTS" \\
        --label-scale "$VOLCANO_LABEL_SCALE"
}}

run_export_and_metrics() {{
    tackle "${{HEADMAIN[@]}}" "$CONF" \\
        export --level gct \\
        metrics
}}

main() {{
    # TODO: uncomment what you want.
    # run_export_and_metrics
    # run_volcano
    :
}}

main "$@"
"""
    return textwrap.dedent(script)


def write_script(path: str, content: str, *, force: bool = False) -> str:
    out_path = Path(path)
    if out_path.exists() and not force:
        raise FileExistsError(f"{out_path} already exists (use --force to overwrite)")
    out_path.write_text(content)
    try:
        mode = out_path.stat().st_mode
        out_path.chmod(mode | 0o111)
    except OSError:
        pass
    return str(out_path)
